# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Postman API Tests 

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: start the app
      run: |
        docker run -d -p 3000:80 -v https://github.com/ShaistaAbbasi/talonone-takehome-task/db.json:/data/db.json clue/json-server
    
    - name: run postman tests
      uses: matt-ball/newman-action@master
      with:
        collection: SocialAppCollection.json
        environment: SocialAppEnvironment.json
